/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qHullJNI_QHullDelaunay */

#ifndef _Included_qHullJNI_QHullDelaunay
#define _Included_qHullJNI_QHullDelaunay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qHullJNI_QHullDelaunay
 * Method:    qHullTriangulate
 * Signature: ([[DZ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_qHullJNI_QHullDelaunay_qHullTriangulate
  (JNIEnv *, jclass, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
